services:
  bot:
    build: '.'
    restart: 'unless-stopped'
    depends_on:
      - 'db'
    environment:
      DB: 'mongodb://db/publisher'
      TOKEN: '${TOKEN}'

  db:
    image: 'mongo'
    volumes:
      - 'mongo_data:/data/db'
    restart: 'unless-stopped'

volumes:
  mongo_data:
